title: Brandon G. Smith
description: Academic Homepage for Brandon G. Smith
theme: just-the-docs

url: https://brangsmith..github.io/bgs

aux_links:
  Google Scholar: https://scholar.google.com/citations?user=E8Vq7eEAAAAJ&hl=en&authuser=1
  ORCiD: https://orcid.org/0000-0001-8471-1368
  Twitter/X: https://x.com/brangsmith

color_scheme: dark

search_enabled: false

footer_content: "Copyright &copy; 2024 Brandon G. Smith"


callouts:
  warning:
    title: construct
    color: yellow
