title: Brandon G. Smith
description: Academic Homepage for Brandon G. Smith
theme: just-the-docs

url: https://brangsmith..github.io/bgs

aux_links:
  Google Scholar: https://scholar.google.com/citations?user=E8Vq7eEAAAAJ&hl=en&authuser=1
  ORCiD: https://orcid.org/0000-0001-8471-1368
  Twitter/X: https://x.com/brangsmith
  

search_enabled: false


footer_content: "Copyright &copy; 2023-2024 Brandon G. Smith.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
