title: Brandon G. Smith
description: Academic Homepage for Brandon G. Smith
theme: just-the-docs

url: https://brangsmith..github.io/bgs

aux_links:
  Twitter/X: https://x.com/brangsmith

search_enabled: false

